name = "tokuten-matching"
compatibility_date = "2026-03-15"
main = "worker/index.ts"
assets = { directory = "dist" }

[[d1_databases]]
binding = "DB"
database_name = "tokuten-db"
database_id = "2d6ce011-c50a-4a8b-a9e0-84d9bbb573e3"
migrations_dir = "drizzle"

[[kv_namespaces]]
binding = "SESSIONS"
id = "d0988aa4a0a14956996680cd4cb72708"

[observability]
enabled = true

[triggers]
crons = ["0 0 * * *"]
